#!/usr/bin/env node
/**
 * Bawwab Setup Wizard
 * Interactively generates api/.env for first-time users.
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import crypto from 'node:crypto';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(q, def = '') {
  return new Promise((resolve) => {
    const prompt = def ? `${q} (${def}): ` : `${q}: `;
    rl.question(prompt, (ans) => {
      resolve(ans.trim() || def);
    });
  });
}

function generateSecret() {
  return crypto.randomBytes(32).toString('hex');
}

async function main() {
  console.log('🚪  Bawwab Setup Wizard');
  console.log('   Self-hosted AI Gateway — lets get you configured.\n');

  const envPath = path.resolve(process.cwd(), 'api', '.env');

  if (fs.existsSync(envPath)) {
    const overwrite = await ask('api/.env already exists. Overwrite? (y/N)', 'N');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Your existing .env is preserved.\n');
      rl.close();
      return;
    }
  }

  console.log('\n--- General Settings ---');
  const port = await ask('Port to run Bawwab on', '3001');
  const host = await ask('Host to bind to', '0.0.0.0');
  const nodeEnv = await ask('Environment (development / production)', 'production');

  console.log('\n--- Security (auto-generated if left blank) ---');
  let jwtSecret = await ask('JWT_SECRET');
  if (!jwtSecret) jwtSecret = generateSecret();

  let adminKey = await ask('ADMIN_API_KEY');
  if (!adminKey) adminKey = generateSecret();

  console.log('\n--- AI Provider API Keys (optional but recommended) ---');
  console.log('Leave blank to skip a provider.\n');

  const openai = await ask('OpenAI API Key');
  const gemini = await ask('Google Gemini API Key');
  const deepseek = await ask('DeepSeek API Key');
  const anthropic = await ask('Anthropic API Key');
  const tavily = await ask('Tavily API Key (web search)');
  const jina = await ask('Jina AI API Key (embeddings)');

  const lines = [
    `# Bawwab Environment Configuration`,
    `# Generated by setup wizard`,
    ``,
    `PORT=${port}`,
    `HOST=${host}`,
    `NODE_ENV=${nodeEnv}`,
    ``,
    `JWT_SECRET=${jwtSecret}`,
    `ADMIN_API_KEY=${adminKey}`,
    ``
  ];

  if (openai) lines.push(`OPENAI_API_KEY=${openai}`);
  if (gemini) lines.push(`GEMINI_API_KEY=${gemini}`);
  if (deepseek) lines.push(`DEEPSEEK_API_KEY=${deepseek}`);
  if (anthropic) lines.push(`ANTHROPIC_API_KEY=${anthropic}`);
  if (tavily) lines.push(`TAVILY_API_KEY=${tavily}`);
  if (jina) lines.push(`JINA_API_KEY=${jina}`);

  lines.push('');

  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');

  console.log(`\n✅  Configuration written to: ${envPath}\n`);
  console.log('--- Summary ---');
  console.log(`Port:      ${port}`);
  console.log(`Host:      ${host}`);
  console.log(`JWT:       ${jwtSecret.slice(0, 8)}...`);
  console.log(`Admin Key: ${adminKey.slice(0, 8)}...`);
  console.log(`Providers: ${[openai&&'OpenAI', gemini&&'Gemini', deepseek&&'DeepSeek', anthropic&&'Anthropic', tavily&&'Tavily', jina&&'Jina'].filter(Boolean).join(', ') || 'none configured yet'}`);
  console.log('\nNext steps:');
  console.log('  npm run build');
  console.log('  npm start');
  console.log(`  Open http://${host === '0.0.0.0' ? 'localhost' : host}:${port} in your browser.\n`);

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
